/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-routes-index.ts
 * Run: npm run build:routes-index
 */

import { analyticsRouter } from '../../config/api/analytics.routes';
import { commentsRouter } from '../../config/api/comments.routes';
import { cyclesRouter } from '../../config/api/cycles.routes';
import { projectsRouter } from '../../config/api/projects.routes';
import { tasksRouter } from '../../config/api/tasks.routes';

export const apiRoutes = [
  { path: '/analytics', router: analyticsRouter },
  { path: '/comments', router: commentsRouter },
  { path: '/cycles', router: cyclesRouter },
  { path: '/projects', router: projectsRouter },
  { path: '/tasks', router: tasksRouter }
];

export type ApiRoutesType = typeof apiRoutes;
