/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-routes-index.ts
 * Run: npm run build:routes-index
 */

import { budgetsRouter } from '../../config/api/budgets.routes';
import { expenseAnalyticsRouter } from '../../config/api/expense-analytics.routes';
import { expenseCategoriesRouter } from '../../config/api/expense-categories.routes';
import { expensesRouter } from '../../config/api/expenses.routes';
import { paymentAccountsRouter } from '../../config/api/payment-accounts.routes';
import { vendorsRouter } from '../../config/api/vendors.routes';

export const apiRoutes = [
  { path: '/budgets', router: budgetsRouter },
  { path: '/expense-analytics', router: expenseAnalyticsRouter },
  { path: '/expense-categories', router: expenseCategoriesRouter },
  { path: '/expenses', router: expensesRouter },
  { path: '/payment-accounts', router: paymentAccountsRouter },
  { path: '/vendors', router: vendorsRouter }
];

export type ApiRoutesType = typeof apiRoutes;
