import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// ===========================================================================
//  AUTO-GENERATED FROM JSON SCHEMA CONFIGS
//  DO NOT EDIT THIS FILE DIRECTLY - Edit config/schema/*.json instead
//  Generated: 2026-01-28T05:20:07.917Z
// ===========================================================================

// Application users
export const users = sqliteTable('users', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name').notNull(),
  email: text('email').unique().notNull(),
  passwordHash: text('password_hash').notNull(),
  role: text('role', { enum: ['admin', 'user'] }).default('user'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});



// ===========================================================================
//  TYPE EXPORTS
// ===========================================================================

export type Users = typeof users.$inferSelect;
export type NewUsers = typeof users.$inferInsert;

