import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// ===========================================================================
//  AUTO-GENERATED FROM JSON SCHEMA CONFIGS
//  DO NOT EDIT THIS FILE DIRECTLY - Edit config/schema/*.json instead
//  Generated: 2026-01-28T07:09:47.685Z
// ===========================================================================

// Tags for categorizing todos
export const tags = sqliteTable('tags', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name').unique().notNull(),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});

// Application users
export const users = sqliteTable('users', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name').notNull(),
  email: text('email').unique().notNull(),
  passwordHash: text('password_hash').notNull(),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});

// Lists of todos belonging to a user
export const todoLists = sqliteTable('todo_lists', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  userId: text('user_id').notNull().references(() => users.id),
  title: text('title').notNull(),
  description: text('description'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});

// Individual todo items
export const todos = sqliteTable('todos', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  listId: text('list_id').notNull().references(() => todoLists.id),
  title: text('title').notNull(),
  description: text('description'),
  dueDate: text('due_date'),
  completed: integer('completed').notNull().default(0),
  priority: text('priority', { enum: ['low', 'medium', 'high'] }),
  order: integer('order'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});

// Many-to-many relationship between todos and tags
export const todoTags = sqliteTable('todo_tags', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  todoId: text('todo_id').notNull().references(() => todos.id),
  tagId: text('tag_id').notNull().references(() => tags.id),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`),
});

// ===========================================================================
//  TYPE EXPORTS
// ===========================================================================

export type Tags = typeof tags.$inferSelect;
export type NewTags = typeof tags.$inferInsert;

export type Users = typeof users.$inferSelect;
export type NewUsers = typeof users.$inferInsert;

export type TodoLists = typeof todoLists.$inferSelect;
export type NewTodoLists = typeof todoLists.$inferInsert;

export type Todos = typeof todos.$inferSelect;
export type NewTodos = typeof todos.$inferInsert;

export type TodoTags = typeof todoTags.$inferSelect;
export type NewTodoTags = typeof todoTags.$inferInsert;

