/**
 * Auto-generated API configs index
 * Generated by scripts/build-api-index.ts
 * DO NOT EDIT MANUALLY
 */

import config_0 from '../../config/api/projects.json';
import config_1 from '../../config/api/tasks.json';
import config_2 from '../../config/api/users.json';

export const apiConfigs = [
  config_0,
  config_1,
  config_2
];
