/**
 * API Config Loader
 *
 * Loads API configuration files from pre-generated index.
 * The index is generated by scripts/build-api-index.ts at build time.
 */

import type { ApiConfig } from './engine/route-engine';

/**
 * Load all API configs from generated index
 */
export async function loadApiConfigs(): Promise<Record<string, ApiConfig>> {
  try {
    // Import from generated index file
    const { apiConfigs } = await import('./configs.generated');

    console.log(`[Config Loader] Loaded ${Object.keys(apiConfigs).length} API configs`);

    return apiConfigs as Record<string, ApiConfig>;
  } catch (error) {
    console.error('[Config Loader] Error loading API configs:', error);
    console.error('[Config Loader] Make sure to run: bun run build:api-index');
    return {};
  }
}

/**
 * Get a single API config by resource name
 */
export async function getApiConfig(resource: string): Promise<ApiConfig | null> {
  const configs = await loadApiConfigs();
  return configs[resource] || null;
}
