/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-api-index.ts
 * Run: npm run build:api-index
 */

import config0 from '../../config/api/projects.json';

export const apiConfigs = {
  'projects': config0
};

export type ApiConfigsType = typeof apiConfigs;
