/**
 * Dynamic API Config Loader
 *
 * Loads all API configs from pre-generated index at build time
 * Uses static imports generated by scripts/build-api-index.ts
 */

import { apiConfigs } from './configs.generated';

export interface ApiConfig {
  resource: string;
  table: string;
  basePath: string;
  [key: string]: any;
}

/**
 * Load all API configs from pre-generated index
 * Configs are statically imported at build time for Cloudflare Workers compatibility
 */
export function loadApiConfigs(): ApiConfig[] {
  // Log each loaded config
  apiConfigs.forEach(config => {
    console.log(`✓ Loaded API config: ${config.resource} (${config.basePath})`);
  });

  return apiConfigs;
}
