/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-routes-index.ts
 * Run: npm run build:routes-index
 */

import { departmentsRouter } from '../../config/api/departments.routes';
import { employeesRouter } from '../../config/api/employees.routes';

export const apiRoutes = [
  { path: '/departments', router: departmentsRouter },
  { path: '/employees', router: employeesRouter }
];

export type ApiRoutesType = typeof apiRoutes;
