import type { Context } from 'hono';
import { drizzle } from 'drizzle-orm/d1';
import { eq, count } from 'drizzle-orm';
import type { ResourceApiConfig } from './types';
import { schemaRegistry } from './schema-registry';
import { coerceValue } from './coerce';
import { success, error, handleError } from '../utils/response';

type Env = { Bindings: { DB: D1Database; JWT_SECRET: string } };

export function createHandler(config: ResourceApiConfig, table: any) {
  return async (c: Context<Env>) => {
    try {
      const db = drizzle(c.env.DB);
      const body = await c.req.json();
      const createConfig = config.create!;

      // Validate required fields
      const missing = createConfig.requiredFields.filter((f) => !body[f]);
      if (missing.length > 0) {
        const e = error(`${missing.join(', ')} ${missing.length === 1 ? 'is' : 'are'} required`, 400);
        return c.json(e.body, e.status);
      }

      // Referential checks (verify referenced records exist)
      for (const check of createConfig.referentialChecks ?? []) {
        if (body[check.field]) {
          const refTable = schemaRegistry[check.table];
          const [exists] = await db
            .select({ id: refTable.id })
            .from(refTable)
            .where(eq(refTable.id, body[check.field]))
            .limit(1);
          if (!exists) {
            const e = error(check.message, 404);
            return c.json(e.body, e.status);
          }
        }
      }

      const id = crypto.randomUUID();

      // Auto-generate fields (e.g., employee code)
      let autoGenerated: Record<string, string> = {};
      if (createConfig.autoGenerate) {
        const ag = createConfig.autoGenerate;
        const [countResult] = await db.select({ value: count() }).from(table);
        const nextNum = countResult.value + 1;

        // Parse pattern: "EMP-{seq:4}" → "EMP-0001"
        let generatedValue = ag.pattern.replace(/\{seq:(\d+)\}/, (_, digits) => {
          return String(nextNum).padStart(parseInt(digits), '0');
        });

        autoGenerated[ag.field] = generatedValue;
      }

      // Build insert values
      const values: Record<string, unknown> = { id };

      // Apply auto-generated values
      Object.assign(values, autoGenerated);

      for (const field of createConfig.fields) {
        if (autoGenerated[field] !== undefined) continue; // skip auto-generated

        if (body[field] !== undefined) {
          // Apply coercion
          if (createConfig.coerce?.[field]) {
            values[field] = coerceValue(body[field], createConfig.coerce[field]);
          } else {
            values[field] = body[field];
          }
        } else if (createConfig.defaults?.[field] !== undefined) {
          values[field] = createConfig.defaults[field];
        } else {
          values[field] = null;
        }
      }

      await db.insert(table).values(values);

      const [created] = await db
        .select()
        .from(table)
        .where(eq(table.id, id))
        .limit(1);

      return c.json(success(created), 201);
    } catch (err) {
      const e = handleError(`Create ${config.resource}`, err);
      return c.json(e.body, e.status);
    }
  };
}
