/**
 * Schema Generator
 *
 * Converts JSON schema configurations to Drizzle ORM TypeScript code.
 * This allows the database schema to be fully config-driven.
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

export interface ColumnConfig {
  name: string;
  type: 'text' | 'integer' | 'real' | 'blob';
  primaryKey?: boolean;
  notNull?: boolean;
  unique?: boolean;
  default?: string | number | boolean;
  defaultFn?: 'uuid';
  enum?: string[];
  references?: {
    table: string;
    column: string;
    onDelete?: string;
  };
  description?: string;
}

export interface IndexConfig {
  name: string;
  columns: string[];
  unique?: boolean;
}

export interface TableConfig {
  table: string;
  description?: string;
  columns: ColumnConfig[];
  indexes?: IndexConfig[];
}

/**
 * Load all schema configs from the config/schema directory.
 */
export function loadSchemaConfigs(schemaDir: string): TableConfig[] {
  const files = readdirSync(schemaDir).filter(f => f.endsWith('.json'));

  return files.map(file => {
    const content = readFileSync(join(schemaDir, file), 'utf-8');
    return JSON.parse(content) as TableConfig;
  });
}

/**
 * Generate Drizzle column definition from column config.
 */
function generateColumnDef(col: ColumnConfig, tableName: string): string {
  let def = '';

  // Start with type
  if (col.enum) {
    def = `text('${toSnakeCase(col.name)}', { enum: [${col.enum.map(v => `'${v}'`).join(', ')}] })`;
  } else {
    def = `${col.type}('${toSnakeCase(col.name)}')`;
  }

  // Add modifiers
  if (col.primaryKey) {
    def += '.primaryKey()';
  }

  if (col.unique) {
    def += '.unique()';
  }

  if (col.notNull) {
    def += '.notNull()';
  }

  // Add default value
  if (col.default !== undefined) {
    if (col.default === 'CURRENT_TIMESTAMP') {
      def += '.default(sql`CURRENT_TIMESTAMP`)';
    } else if (typeof col.default === 'string') {
      def += `.default('${col.default}')`;
    } else {
      def += `.default(${col.default})`;
    }
  }

  // Add default function
  if (col.defaultFn === 'uuid') {
    def += '.$defaultFn(() => crypto.randomUUID())';
  }

  // Add references
  if (col.references) {
    // Handle self-references with type assertion
    if (col.references.table === tableName) {
      def += `.references((): any => ${toCamelCase(col.references.table)}.${col.references.column})`;
    } else {
      def += `.references(() => ${toCamelCase(col.references.table)}.${col.references.column})`;
    }
  }

  return def;
}

/**
 * Generate complete Drizzle schema file from JSON configs.
 */
export function generateSchemaFile(configs: TableConfig[]): string {
  let output = `import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';\n`;
  output += `import { sql } from 'drizzle-orm';\n\n`;

  output += `// ===========================================================================\n`;
  output += `//  AUTO-GENERATED FROM JSON SCHEMA CONFIGS\n`;
  output += `//  DO NOT EDIT THIS FILE DIRECTLY - Edit config/schema/*.json instead\n`;
  output += `//  Generated: ${new Date().toISOString()}\n`;
  output += `// ===========================================================================\n\n`;

  // Sort configs to ensure dependencies come first
  const sortedConfigs = topologicalSort(configs);

  // Generate table definitions
  for (const config of sortedConfigs) {
    const tableName = toCamelCase(config.table);

    if (config.description) {
      output += `// ${config.description}\n`;
    }

    output += `export const ${tableName} = sqliteTable('${config.table}', {\n`;

    for (const col of config.columns) {
      if (col.description) {
        output += `  // ${col.description}\n`;
      }
      output += `  ${col.name}: ${generateColumnDef(col, config.table)},\n`;
    }

    output += `});\n\n`;
  }

  // Generate type exports
  output += `// ===========================================================================\n`;
  output += `//  TYPE EXPORTS\n`;
  output += `// ===========================================================================\n\n`;

  for (const config of sortedConfigs) {
    const tableName = toCamelCase(config.table);
    const typeName = toPascalCase(config.table.replace(/_/g, ' '));

    output += `export type ${typeName} = typeof ${tableName}.$inferSelect;\n`;
    output += `export type New${typeName} = typeof ${tableName}.$inferInsert;\n\n`;
  }

  return output;
}

/**
 * Topological sort to ensure tables are defined before they're referenced.
 */
function topologicalSort(configs: TableConfig[]): TableConfig[] {
  const sorted: TableConfig[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  const configMap = new Map(configs.map(c => [c.table, c]));

  function visit(tableName: string) {
    if (visited.has(tableName)) return;
    if (visiting.has(tableName)) {
      // Circular reference - just continue
      return;
    }

    visiting.add(tableName);

    const config = configMap.get(tableName);
    if (!config) return;

    // Visit dependencies first
    for (const col of config.columns) {
      if (col.references && col.references.table !== tableName) {
        visit(col.references.table);
      }
    }

    visiting.delete(tableName);
    visited.add(tableName);
    sorted.push(config);
  }

  for (const config of configs) {
    visit(config.table);
  }

  return sorted;
}

/**
 * Convert snake_case to camelCase.
 */
function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
}

/**
 * Convert snake_case to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[\s_]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

/**
 * Convert camelCase to snake_case.
 */
function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
}

/**
 * Main function to regenerate schema.ts from JSON configs.
 */
export function regenerateSchema(schemaDir: string, outputFile: string) {
  console.log('Loading schema configs from:', schemaDir);
  const configs = loadSchemaConfigs(schemaDir);

  console.log(`Found ${configs.length} table configs`);

  console.log('Generating schema file...');
  const schemaCode = generateSchemaFile(configs);

  console.log('Writing to:', outputFile);
  writeFileSync(outputFile, schemaCode, 'utf-8');

  console.log('Schema generated successfully!');
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const schemaDir = process.argv[2] || join(process.cwd(), 'config/schema');
  const outputFile = process.argv[3] || join(process.cwd(), 'src/db/schema.generated.ts');

  regenerateSchema(schemaDir, outputFile);
}
