/**
 * Build API Config Index
 *
 * Generates src/api/configs.generated.ts with imports for all API configs
 * Run this before building the worker
 */

import * as fs from 'fs';
import * as path from 'path';

const configDir = path.join(process.cwd(), 'config', 'api');
const outputFile = path.join(process.cwd(), 'src', 'api', 'configs.generated.ts');

if (!fs.existsSync(configDir)) {
  console.error('❌ API config directory not found:', configDir);
  process.exit(1);
}

const files = fs.readdirSync(configDir)
  .filter(file => file.endsWith('.json'))
  .sort();

const imports: string[] = [];
const exports: string[] = [];

files.forEach((file, index) => {
  const name = file.replace('.json', '').replace(/-/g, '_');
  const varName = `config_${index}`;

  imports.push(`import ${varName} from '../../config/api/${file}';`);
  exports.push(`  ${varName}`);
});

const content = `/**
 * Auto-generated API configs index
 * Generated by scripts/build-api-index.ts
 * DO NOT EDIT MANUALLY
 */

${imports.join('\n')}

export const apiConfigs = [
${exports.join(',\n')}
];
`;

fs.writeFileSync(outputFile, content);

console.log(`✅ Generated API config index with ${files.length} configs`);
console.log(`   Output: ${outputFile}`);
