/**
 * Build API Index
 *
 * Generates src/api/configs.generated.ts with static imports for all API configs.
 * This is necessary because import.meta.glob doesn't work in Cloudflare Workers.
 */

import * as fs from 'fs';
import * as path from 'path';

const CONFIG_DIRS = [
  'config/api'
];

interface ConfigFile {
  path: string;
  importPath: string;
  resource: string;
}

function findConfigFiles(): ConfigFile[] {
  const configs: ConfigFile[] = [];

  for (const dir of CONFIG_DIRS) {
    const fullPath = path.resolve(process.cwd(), dir);

    if (!fs.existsSync(fullPath)) {
      console.log(`⚠️  Directory not found: ${dir}`);
      continue;
    }

    const files = fs.readdirSync(fullPath);

    for (const file of files) {
      if (!file.endsWith('.json')) continue;

      const configPath = path.join(fullPath, file);
      const configContent = JSON.parse(fs.readFileSync(configPath, 'utf-8'));

      if (!configContent.resource || !configContent.basePath) {
        console.log(`⚠️  Skipping invalid config: ${file} (missing resource or basePath)`);
        continue;
      }

      // Generate import path relative to src/api/
      const relativePath = path.relative(
        path.resolve(process.cwd(), 'src/api'),
        configPath
      ).replace(/\\/g, '/');

      configs.push({
        path: configPath,
        importPath: relativePath,
        resource: configContent.resource
      });
    }
  }

  return configs;
}

function generateIndexFile(configs: ConfigFile[]): string {
  const imports = configs
    .map((config, index) => `import config${index} from '${config.importPath}';`)
    .join('\n');

  const exports = configs
    .map((config, index) => `  '${config.resource}': config${index}`)
    .join(',\n');

  return `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-api-index.ts
 * Run: npm run build:api-index
 */

${imports}

export const apiConfigs = {
${exports}
};

export type ApiConfigsType = typeof apiConfigs;
`;
}

function main() {
  console.log('🔨 Building API config index...\n');

  const configs = findConfigFiles();

  if (configs.length === 0) {
    console.log('⚠️  No API configs found');
    process.exit(0);
  }

  console.log(`📋 Found ${configs.length} API configs:`);
  configs.forEach(config => {
    console.log(`   - ${config.resource} (${config.path})`);
  });

  const outputPath = path.resolve(process.cwd(), 'src/api/configs.generated.ts');
  const content = generateIndexFile(configs);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(`\n✅ Generated ${outputPath}`);
  console.log(`   Exported ${configs.length} API configs\n`);
}

main();
