/**
 * Build Routes Index
 *
 * Generates src/api/routes.generated.ts with static imports for all TypeScript route files.
 * This scans config/api/*.routes.ts and creates a registry of routers.
 */

import * as fs from 'fs';
import * as path from 'path';

const CONFIG_DIR = 'config/api';

interface RouteFile {
  path: string;
  importPath: string;
  basePath: string;
  routerName: string;
}

function findRouteFiles(): RouteFile[] {
  const routes: RouteFile[] = [];
  const fullPath = path.resolve(process.cwd(), CONFIG_DIR);

  if (!fs.existsSync(fullPath)) {
    console.log(`⚠️  Directory not found: ${CONFIG_DIR}`);
    return routes;
  }

  const files = fs.readdirSync(fullPath);

  for (const file of files) {
    if (!file.endsWith('.routes.ts')) continue;

    const routePath = path.join(fullPath, file);

    // Extract base path from filename (e.g., employees.routes.ts -> employees)
    const baseName = file.replace('.routes.ts', '');

    // Generate import path relative to src/api/
    const relativePath = path.relative(
      path.resolve(process.cwd(), 'src/api'),
      routePath
    ).replace(/\\/g, '/');

    routes.push({
      path: routePath,
      importPath: relativePath,
      basePath: `/${baseName}`,
      routerName: `${baseName}Router`
    });
  }

  return routes;
}

function generateIndexFile(routes: RouteFile[]): string {
  const imports = routes
    .map(route => `import { ${route.routerName} } from '${route.importPath.replace(/\.ts$/, '')}';`)
    .join('\n');

  const routesList = routes
    .map(route => `  { path: '${route.basePath}', router: ${route.routerName} }`)
    .join(',\n');

  return `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/build-routes-index.ts
 * Run: npm run build:routes-index
 */

${imports}

export const apiRoutes = [
${routesList}
];

export type ApiRoutesType = typeof apiRoutes;
`;
}

function main() {
  console.log('🔨 Building API routes index...\n');

  const routes = findRouteFiles();

  if (routes.length === 0) {
    console.log('⚠️  No route files found');
    process.exit(0);
  }

  console.log(`📋 Found ${routes.length} route files:`);
  routes.forEach(route => {
    console.log(`   - ${route.basePath} (${route.path})`);
  });

  const outputPath = path.resolve(process.cwd(), 'src/api/routes.generated.ts');
  const content = generateIndexFile(routes);

  fs.writeFileSync(outputPath, content, 'utf-8');

  console.log(`\n✅ Generated ${outputPath}`);
  console.log(`   Exported ${routes.length} route files\n`);
}

main();
